INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_RCCBLOCKS rccBlocks)

FIND_PATH(
    RCCBLOCKS_INCLUDE_DIRS
    NAMES rccBlocks/api.h
    HINTS $ENV{RCCBLOCKS_DIR}/include
        ${PC_RCCBLOCKS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    RCCBLOCKS_LIBRARIES
    NAMES gnuradio-rccBlocks
    HINTS $ENV{RCCBLOCKS_DIR}/lib
        ${PC_RCCBLOCKS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RCCBLOCKS DEFAULT_MSG RCCBLOCKS_LIBRARIES RCCBLOCKS_INCLUDE_DIRS)
MARK_AS_ADVANCED(RCCBLOCKS_LIBRARIES RCCBLOCKS_INCLUDE_DIRS)

